<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharingKnowledge.Data.Models\SharingKnowledge.Data.Models.csproj" />
    <ProjectReference Include="..\SharingKnowledge.Data\SharingKnowledge.Data.csproj" />
    <ProjectReference Include="..\SharingKnowledge.Services.Common\SharingKnowledge.Services.Common.csproj" />
    <ProjectReference Include="..\SharingKnowledge.Web.ViewModels\SharingKnowledge.Web.ViewModels.csproj" />
  </ItemGroup>

</Project>
