<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharingKnowledge.Common\SharingKnowledge.Common.csproj" />
    <ProjectReference Include="..\SharingKnowledge.Data.Models\SharingKnowledge.Data.Models.csproj" />
  </ItemGroup>

</Project>
